# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McUyCbG1Oaz34jMhNBfkNuToxkYt7CAE
"""

# ===============================================================
# FREESTYLE SWIMMING TECHNIQUE – WEB DASHBOARD
# Streamlit App
# ===============================================================

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

st.set_page_config(
    page_title="Freestyle Technique Dashboard",
    layout="wide"
)

st.title("🏊 Freestyle Swimming Technique Dashboard")

# ===============================================================
# FILE UPLOAD
# ===============================================================
st.sidebar.header("Upload Analysis Files")

csv_file = st.sidebar.file_uploader(
    "Upload swim_analysis_*.csv",
    type=["csv"]
)

video_file = st.sidebar.file_uploader(
    "Upload annotated_swim_*.mp4",
    type=["mp4"]
)

if csv_file is None:
    st.info("⬅ Upload your CSV file to begin")
    st.stop()

# ===============================================================
# LOAD DATA
# ===============================================================
df = pd.read_csv(csv_file)

required_cols = {
    "time", "elbow", "knee_L", "knee_R",
    "symmetry", "score", "yaw", "breath"
}

if not required_cols.issubset(df.columns):
    st.error("CSV file does not match expected format.")
    st.stop()

# ===============================================================
# KPIs
# ===============================================================
duration_s = df["time"].iloc[-1]
avg_score = df["score"].mean()
avg_sym = df["symmetry"].mean()

# Stroke rate estimation
stroke_times = df.loc[df["elbow"].diff().abs() > 15, "time"]
if len(stroke_times) >= 2:
    sr_both = 120 * (len(stroke_times) - 1) / max(
        1e-6, stroke_times.iloc[-1] - stroke_times.iloc[0]
    )
else:
    sr_both = 0.0

breaths_L = (df["breath"] == "L").sum()
breaths_R = (df["breath"] == "R").sum()
bpm = (breaths_L + breaths_R) / max(1e-6, duration_s / 60)

# ===============================================================
# KPI DISPLAY
# ===============================================================
c1, c2, c3, c4 = st.columns(4)

c1.metric("⏱ Duration (min)", f"{duration_s/60:.1f}")
c2.metric("🎯 Avg Score", f"{avg_score:.1f} / 100")
c3.metric("🔄 Stroke Rate", f"{sr_both:.1f} spm")
c4.metric("🫁 Breaths / min", f"{bpm:.1f}")

# ===============================================================
# BREATHING BIAS
# ===============================================================
if breaths_L > breaths_R * 1.3:
    bias = "⬅ Left-side dominant"
elif breaths_R > breaths_L * 1.3:
    bias = "➡ Right-side dominant"
else:
    bias = "⚖ Balanced breathing"

st.subheader("Breathing Pattern")
st.write(
    f"**Left:** {breaths_L}  "
    f"**Right:** {breaths_R}  "
    f"**Bias:** {bias}"
)

# ===============================================================
# VIDEO PLAYER
# ===============================================================
if video_file:
    st.subheader("Annotated Technique Video")
    st.video(video_file)

# ===============================================================
# TIME-SERIES PLOTS
# ===============================================================
st.subheader("Technique Time Series")

fig, axs = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

# Angles
axs[0].plot(df["time"], df["elbow"], label="Elbow")
axs[0].plot(df["time"], df["knee_L"], label="Knee L")
axs[0].plot(df["time"], df["knee_R"], label="Knee R")
axs[0].set_ylabel("Angle (°)")
axs[0].legend()
axs[0].grid(alpha=0.3)

# Symmetry + Score
axs[1].plot(df["time"], df["symmetry"], label="Symmetry")
axs[1].plot(df["time"], df["score"], label="Score", alpha=0.7)
axs[1].set_ylabel("Value")
axs[1].legend()
axs[1].grid(alpha=0.3)

# Score with breath markers
axs[2].plot(df["time"], df["score"], label="Score", color="green")

for i in range(1, len(df)):
    if df["breath"].iloc[i] != df["breath"].iloc[i-1]:
        if df["breath"].iloc[i] == "L":
            axs[2].axvline(df["time"].iloc[i], linestyle=":", alpha=0.6)
        elif df["breath"].iloc[i] == "R":
            axs[2].axvline(df["time"].iloc[i], linestyle="--", alpha=0.6)

axs[2].set_xlabel("Time (s)")
axs[2].legend()
axs[2].grid(alpha=0.3)

st.pyplot(fig)

# ===============================================================
# DATA TABLE
# ===============================================================
st.subheader("Raw Frame Data")
st.dataframe(df, height=300)

# ===============================================================
# DOWNLOAD
# ===============================================================
st.download_button(
    "⬇ Download CSV",
    data=df.to_csv(index=False).encode("utf-8"),
    file_name="swim_analysis.csv",
    mime="text/csv"
)

st.success("Dashboard ready ✅")